/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Thrift;
using Thrift.Protocol;
using Thrift.Transport;
public class batch_mutation_super_t 
{
  public string table;
  public string key;
  public Dictionary<string, List<superColumn_t>> cfmap;

  public Isset __isset;
  public struct Isset {
    public bool table;
    public bool key;
    public bool cfmap;
  }

  public batch_mutation_super_t() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    TStruct struc = iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            this.table = iprot.ReadString();
            this.__isset.table = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            this.key = iprot.ReadString();
            this.__isset.key = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.Map) {
            {
              this.cfmap = new Dictionary<string, List<superColumn_t>>();
              TMap _map13 = iprot.ReadMapBegin();
              for( int _i14 = 0; _i14 < _map13.Count; ++_i14)
              {
                string _key15;
                List<superColumn_t> _val16;
                _key15 = iprot.ReadString();
                {
                  _val16 = new List<superColumn_t>();
                  TList _list17 = iprot.ReadListBegin();
                  for( int _i18 = 0; _i18 < _list17.Count; ++_i18)
                  {
                    superColumn_t _elem19 = new superColumn_t();
                    _elem19 = new superColumn_t();
                    _elem19.Read(iprot);
                    _val16.Add(_elem19);
                  }
                  iprot.ReadListEnd();
                }
                this.cfmap[_key15] = _val16;
              }
              iprot.ReadMapEnd();
            }
            this.__isset.cfmap = true;
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("batch_mutation_super_t");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (this.table != null) {
      field.Name = "table";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(this.table);
      oprot.WriteFieldEnd();
    }
    if (this.key != null) {
      field.Name = "key";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(this.key);
      oprot.WriteFieldEnd();
    }
    if (this.cfmap != null) {
      field.Name = "cfmap";
      field.Type = TType.Map;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.List, this.cfmap.Count));
        foreach (string _iter20 in this.cfmap.Keys)
        {
          oprot.WriteString(_iter20);
          {
            oprot.WriteListBegin(new TList(TType.Struct, this.cfmap[_iter20].Count));
            foreach (superColumn_t _iter21 in this.cfmap[_iter20])
            {
              _iter21.Write(oprot);
              oprot.WriteListEnd();
            }
          }
          oprot.WriteMapEnd();
        }
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("batch_mutation_super_t(");
    sb.Append("table: ");
    sb.Append(this.table);
    sb.Append(",key: ");
    sb.Append(this.key);
    sb.Append(",cfmap: ");
    sb.Append(this.cfmap);
    sb.Append(")");
    return sb.ToString();
  }

}

