/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "cassandra_constants.h"

namespace com { namespace facebook { namespace infrastructure { namespace service {

const cassandraConstants g_cassandra_constants;

cassandraConstants::cassandraConstants() {
}

}}}} // namespace

