#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'
require File.dirname(__FILE__) + '/fb303_types'


class Column_t
  include Thrift::Struct
  Thrift::Struct.field_accessor self, :columnName, :value, :timestamp
  FIELDS = {
    1 => {:type => Thrift::Types::STRING, :name => 'columnName'},
    2 => {:type => Thrift::Types::STRING, :name => 'value'},
    3 => {:type => Thrift::Types::I32, :name => 'timestamp'}
  }
end

class Batch_mutation_t
  include Thrift::Struct
  Thrift::Struct.field_accessor self, :table, :key, :cfmap
  FIELDS = {
    1 => {:type => Thrift::Types::STRING, :name => 'table'},
    2 => {:type => Thrift::Types::STRING, :name => 'key'},
    3 => {:type => Thrift::Types::MAP, :name => 'cfmap', :key => {:type => Thrift::Types::STRING}, :value => {:type => Thrift::Types::LIST, :element => {:type => Thrift::Types::STRUCT, :class => Column_t}}}
  }
end

class SuperColumn_t
  include Thrift::Struct
  Thrift::Struct.field_accessor self, :name, :columns
  FIELDS = {
    1 => {:type => Thrift::Types::STRING, :name => 'name'},
    2 => {:type => Thrift::Types::LIST, :name => 'columns', :element => {:type => Thrift::Types::STRUCT, :class => Column_t}}
  }
end

class Batch_mutation_super_t
  include Thrift::Struct
  Thrift::Struct.field_accessor self, :table, :key, :cfmap
  FIELDS = {
    1 => {:type => Thrift::Types::STRING, :name => 'table'},
    2 => {:type => Thrift::Types::STRING, :name => 'key'},
    3 => {:type => Thrift::Types::MAP, :name => 'cfmap', :key => {:type => Thrift::Types::STRING}, :value => {:type => Thrift::Types::LIST, :element => {:type => Thrift::Types::STRUCT, :class => SuperColumn_t}}}
  }
end

