(*
 Autogenerated by Thrift

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
class column_t :
object
  method get_columnName : string option
  method grab_columnName : string
  method set_columnName : string -> unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method get_timestamp : int option
  method grab_timestamp : int
  method set_timestamp : int -> unit
  method write : Protocol.t -> unit
end
val read_column_t : Protocol.t -> column_t
class batch_mutation_t :
object
  method get_table : string option
  method grab_table : string
  method set_table : string -> unit
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method get_cfmap : (string,column_t list) Hashtbl.t option
  method grab_cfmap : (string,column_t list) Hashtbl.t
  method set_cfmap : (string,column_t list) Hashtbl.t -> unit
  method write : Protocol.t -> unit
end
val read_batch_mutation_t : Protocol.t -> batch_mutation_t
class superColumn_t :
object
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method get_columns : column_t list option
  method grab_columns : column_t list
  method set_columns : column_t list -> unit
  method write : Protocol.t -> unit
end
val read_superColumn_t : Protocol.t -> superColumn_t
class batch_mutation_super_t :
object
  method get_table : string option
  method grab_table : string
  method set_table : string -> unit
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method get_cfmap : (string,superColumn_t list) Hashtbl.t option
  method grab_cfmap : (string,superColumn_t list) Hashtbl.t
  method set_cfmap : (string,superColumn_t list) Hashtbl.t -> unit
  method write : Protocol.t -> unit
end
val read_batch_mutation_super_t : Protocol.t -> batch_mutation_super_t
type column_family_map = (string,column_t list) Hashtbl.t

type superColumn_family_map = (string,superColumn_t list) Hashtbl.t

